### PR TITLE
Added themeDir to localize_scripts function

### PR DESCRIPTION
**Pull request by jonXmack**
Allows theme directory to be used in js

### CODE REVIEW

**Comment by danimalweb** [comment]
Check with @mrchimp on the naming of the variable. themeDir or theme_url / themeURL?

**Comment by jonXmack** [comment]
I'll ask when he's back in the office

**Comment by mrchimp** [comment]
Our style guide says camelCase for JS variable names and that fits with what we already have in Tofino.

**Comment by danimalweb** [comment]
Please update the variable name to themeUrl to make it consistent with the other variable names already in use and your style guide (aka AirBnb). Thanks!

**Pull request merged**
