### PR TITLE
[WIP] Tofino v1.2.0

### PR DESCRIPTION
**Pull request by danimalweb**
- [x] Refactor gulpfile.js and split gulp tasks (and use eslint)
- [x] Update npm dependencies
- [x] Polyfill IE11 flexbox issues
- [x] Fix BrowserSync css injection
- [x] Add WPML template compatibility
- [x] Docblock all functions and files
- [x] Add AjaxForm class
- [x] Update README to include info about deployment
- [x] Replace OptionTree with WP Customizer for theme options
- [x] Remove unit tests until a better solution is implemented
- [x] Include default social network links and icons

### CODE REVIEW

**Comment by danimalweb** [comment]
@mrchimp @jonXmack New release ready at my end. One of you fancy pulling down the dev branch and giving it a quick test?

**Comment by jonXmack** [comment]
All seems okay to me. Apart from not being able to get anything from `echo do_shortcode('social_icons');` but that is more likely to be a mistake on my part.

**Comment by danimalweb** [comment]
@jonXmack I believe the correct syntax is ```echo do_shortcode('[social_icons]');``` (Add sqaure brackets).

**Comment by jonXmack** [comment]
Okay cool. That gives me `Notice: Undefined index: social in /src/shortcodes.php on line 101` which is the same error that displays from `echo social_icons();`

**Comment by jonXmack** [comment]
Is there any way we can easily add/remove/reorder the social links? Ours tend to vary from client to client and the old system was great for that, I've modified the `theme-options.php` file for the site I'm testing 1.2 on so I can use IG instead of LinkedIn but when it comes to adding new ones it's (obviously) not quite as easy as it was.

**Comment by danimalweb** [comment]
Easily out of the box? No. Easily with some work? Yes. 

The WP Customizer does not come with built-in repeater rows, or drag and drop re-ordering. I've seen both achieved by extending the WP_Customizer class and creating a custom control and associated javascript. I definitely want to make this and it will be useful for other options, but it might not get in the 1.2 release.

**Comment by jonXmack** [comment]
That's cool, there's no rush, I'm happy copy and pasting to add/reorder them. Jake did quite rightly mention that any that would be added would have to have the associated icon anyway which would require access to the codebase so it's probably not as much of an issue as I initially thought.

**Comment by danimalweb** [comment]
@jonXmack after chatting with @mrchimp I've added some default social networks with svg icons included. Ref #143.

**Pull request merged**
